---
title: "Calibration Visualization"
author: "Benjamin E. deMayo"
date: "May 10, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(psych)
library(langcog)
library(tidyverse)
library(stringr)
library(magrittr)
library(lmerTest)
library(fs)

source(path(here::here(), "file_paths.R")) #reads in externally-defined file paths

calibration_file <- 
  path(
    project_root, 
    "analysis", 
    "calibration_sanity_check", 
    "test_benny_5_3-eye_data Samples.txt"
  )

calibration_seconds <- 11
```

```{r}
#This function reads in data that end in .txt

read.smi.idf <- function(file.name) {
  d <- 
    read_tsv(
    file.name, 
    comment = "##"
    ) %>% 
    filter(Type == "SMP") %>% 
    select(
      t = Time,
      lx = "L POR X [px]",
      rx = "R POR X [px]",
      ly = "L POR Y [px]",
      ry = "R POR Y [px]"
    ) %>% 
    mutate(sid = str_extract(file.name, "\\d{6}_\\d{2}"))
}

```

```{r}
################################################################################
## PREPROCESS DATA 
## take data file with l and r, x and y, as well as stimulus, average
## eyes, do whatever preprocessing needs to be done. 
################################################################################

preprocess.data <- function(d, x.max = 1920, y.max=1080, samp.rate = 30) {

  #Remove out of range looks
    d <- 
    d %>% 
    mutate(
      rx = if_else(rx <= 0 | rx >= x.max, NA_real_, rx),
      lx = if_else(lx <= 0 | lx >= x.max, NA_real_, lx),
      ry = if_else(ry <= 0 | ry >= y.max, NA_real_, ry),
      ly = if_else(ly <= 0 | ly >= y.max, NA_real_, ly)
    )

  #Take one eye if we only have one; otherwise average them
    d <-
      d %>%
      mutate(
        x = case_when(
          is.na(rx) & !is.na(lx) ~ lx,
          !is.na(rx) & is.na(lx) ~ rx,
          !is.na(rx) & !is.na(lx) ~ (rx + lx) / 2,
          is.na(rx) & is.na(lx) ~ NA_real_
        ),
        y = case_when(
          is.na(ry) & !is.na(ly) ~ ly,
          !is.na(ry) & is.na(ly) ~ ry,
          !is.na(ry) & !is.na(ly) ~ (ry + ly) / 2,
          is.na(ry) & is.na(ly) ~ NA_real_
        )
      ) %>%
      select(
        -rx, -ry, -lx, -ly
      ) %>%
      mutate(
        t = round((d$t - d$t[1])/(1000000), 3),
        y = y.max - y
      )
}
```

```{r}

d_calibration <- 
  read.smi.idf(calibration_file) %>% preprocess.data()

d_calibration %>% 
  filter(t <= 2) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  theme_minimal() +
  labs(title = "Calibration after 2 seconds")

d_calibration %>% 
  filter(t <= 4) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  labs(title = "Calibration after 4 seconds") +
  theme_minimal() 

d_calibration %>% 
  filter(t <= 7) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  labs(title = "Calibration after 7 seconds") +
  theme_minimal() 

d_calibration %>% 
  filter(t <= 9) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  labs(title = "Calibration after 9 seconds") +
  theme_minimal() 

d_calibration %>% 
  filter(t <= 11) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  labs(title = "Calibration after 11 seconds (completion)") +
  theme_minimal() 

d_calibration %>% 
  filter(t <= 13) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  labs(title = "Calibration after 16 seconds (completion)") +
  theme_minimal() 

d_calibration %>% 
  filter(t > 16 & t < 18) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  theme_minimal() 

d_calibration %>% 
  filter(t > 18 & t < 20) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  theme_minimal() 

d_calibration %>% 
  filter(t > 20 & t < 22) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  theme_minimal() 

d_calibration %>% 
  filter(t > 22 & t < 23.5) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  theme_minimal() 

d_calibration %>% 
  filter(t > 23.5 & t < 27) %>% 
  ggplot(aes(x, y)) +
  geom_point(alpha = 0.5) +
  coord_cartesian(xlim = c(450, 1400), ylim = c(800, 200)) +
  theme_minimal() 


```

