---
title: "soc_ref_cat_analysis_2"
author: "Benjamin E. deMayo"
date: "March 8, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(psych)
library(langcog)
library(tidyverse)
library(stringr)
library(magrittr)
library(lmerTest)

example_file <- "raw_data/020218_01-eye_data Samples.txt"

example_trial_file <- "trial_data/020218_01.csv"

demographics_sheet <- "soc_ref_cat_demo_github.csv"

key <- "trial_morphs.csv"
```

Preliminaries.

```{r}
#read in trial data.

demographics <- read_csv(demographics_sheet)

# example_f <- 
#   read_csv(example_trial_file)
# 
# condition_test <- 
#   demographics %>% 
#   filter(SID == "020218_01") %>% 
#   pull(Condition)
# 
# condition_test


include <- 
  demographics %>% 
  filter(Exclude == "n") 

trial_key <- read_csv(key)

d_trials <- data_frame()
files <- dir("trial_data")

for (f in files) {
  
  subj_id <- str_replace(f, ".csv", "")
  
  condition <- 
    demographics %>% 
    filter(`SID` == subj_id) %>% 
    pull("Condition")

  
  jf <- paste("trial_data/", f, sep = "")
  jd <- read_csv(jf)
  id <- 
    tibble(
      SID = subj_id, 
      trial = jd$Trial.Number,  
      onset = jd$Trial.onset / 1000,  
      offset = jd$Trial.offset / 1000,
      chosen_side = jd$Trial.side
    ) %>%
    mutate(
      camera_onset = jd$camera.onset[1] / 1000,
      webcam_onset = jd$webcam.onset[1] / 1000,
      camera_lag = webcam_onset - camera_onset,
      webcam_length = jd$extcam_length.onset[1] / 1000,
      onset = onset + camera_lag,
      offset = offset + camera_lag

    )
  d_trials <- bind_rows(d_trials, id)
  
}

d_trials <- 
  d_trials  %>%
  left_join(
    demographics %>% select(SID, Condition),
    by = c("SID")
  ) %>%
  left_join(
    trial_key,
    by = c("trial" = "Trial", "Condition")
  ) %>%
  mutate(
    accuracy = case_when(
       correct_side == "M" ~ NA,
       correct_side != "M" ~ correct_side == chosen_side
    )
   ) %>%
  left_join(
    demographics %>% select(SID, age),
    by = "SID"
  )
```

```{r}
#This function reads in data that end in .txt

read.smi.idf <- function(file.name) {
  d <- 
    read_tsv(
    file.name, 
    comment = "##"
    ) %>% 
    filter(Type == "SMP") %>% 
    select(
      t = Time,
      lx = "L POR X [px]",
      rx = "R POR X [px]",
      ly = "L POR Y [px]",
      ry = "R POR Y [px]"
    ) %>% 
    mutate(sid = str_extract(file.name, "\\d{6}_\\d{2}"))
}
```

```{r}
################################################################################
## PREPROCESS DATA 
## take data file with l and r, x and y, as well as stimulus, average
## eyes, do whatever preprocessing needs to be done. 
################################################################################

preprocess.data <- function(d, x.max = 1920, y.max=1080, samp.rate = 30) {

  #Remove out of range looks
    d <- 
    d %>% 
    mutate(
      rx = if_else(rx <= 0 | rx >= x.max, NA_real_, rx),
      lx = if_else(lx <= 0 | lx >= x.max, NA_real_, lx),
      ry = if_else(ry <= 0 | ry >= y.max, NA_real_, ry),
      ly = if_else(ly <= 0 | ly >= y.max, NA_real_, ly)
    )

  #Take one eye if we only have one; otherwise average them
    d <-
      d %>%
      mutate(
        x = case_when(
          is.na(rx) & !is.na(lx) ~ lx,
          !is.na(rx) & is.na(lx) ~ rx,
          !is.na(rx) & !is.na(lx) ~ (rx + lx) / 2,
          is.na(rx) & is.na(lx) ~ NA_real_
        ),
        y = case_when(
          is.na(ry) & !is.na(ly) ~ ly,
          !is.na(ry) & is.na(ly) ~ ry,
          !is.na(ry) & !is.na(ly) ~ (ry + ly) / 2,
          is.na(ry) & is.na(ly) ~ NA_real_
        )
      ) %>%
      select(
        -rx, -ry, -lx, -ly
      ) %>%
      mutate(
        t = round((d$t - d$t[1])/(1000000), 3),
        y = y.max - y
      )
}
```

Read in experiment data and preprocess.
```{r}
raw.data.path <- "raw_data/"
processed.data.path <- "processed_data/"

## LOOP TO READ IN FILES
all_data <- data_frame()
files <- dir(raw.data.path,pattern = "*.txt")

to.n <- function(x) {as.numeric(as.character(x))}
sem <- function(x) {sd(x) / sqrt(length(x))}

a <-  0
for (file.name in files) {
  a = a + 1
}

for (file.name in files) {
  ## print file name, so if loop breaks, we know where
  print(file.name)
  exp_trials <-
    d_trials %>%
    filter(SID == str_extract(file.name, "\\d{6}_\\d{2}"))
  
  print(exp_trials)

  ## these are the two functions that are most meaningful
  d <- read.smi.idf(str_c(raw.data.path, file.name, sep = ""))
  d <- preprocess.data(d, x.max = 1920, y.max = 1080, samp.rate = 30) 
  
  calibration_time <- d$t[nrow(d)] - exp_trials$webcam_length[1]

  d %<>% 
    mutate(t = t - calibration_time) %>% 
    filter(t >= 0)
  
  d_trial <- 
    exp_trials %>%
    split(.$trial) %>%
    map_df(function(trial_row) {
      this_trial <- filter(d, t >= trial_row$onset, t < trial_row$offset) %>%
        mutate(trial = trial_row$trial) %>%
        left_join(trial_row)
      
      return(this_trial)
    })
  
  ## now here's where data get bound togetherq
  all_data <- bind_rows(all_data, d_trial)
}

write_csv(all_data, path = paste0(processed.data.path, "socref_cat_data.csv"))




```

```{r}
#Accuracy checks


d_trials_block <- 
  d_trials %>% 
  mutate(
    block = case_when(
      1 <= trial & trial <= 7 ~ 1,
      8 <= trial & trial <= 14 ~ 2,
      15 <= trial & trial <= 21 ~ 3,
      22 <= trial & trial <= 28 ~ 4
    )
  )

d_accuracy_morph <- 
  d_trials_block %>%
  filter(Morph != 50) %>% 
  group_by(SID, Morph) %>% 
  summarize(accuracy = mean(accuracy, na.rm = TRUE)) %>% 
  group_by(Morph) %>% 
  multi_boot_standard(col = "accuracy") %>% 
  ungroup()

d_accuracy_morph %>% 
  ggplot(aes(x = Morph, y = mean)) + 
  geom_line(size = .5) + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper)) +
  geom_hline(yintercept = .5, lty = 2) + 
  ylim(0,1) + 
  ylab("Proportion Accurate") + 
  xlab("Morph level") + 
  labs(
    title = "Mean Accuracy by Morph Level"
  ) +
  ggthemes::theme_few() +
  scale_x_continuous(breaks = c(60, 70, 100)) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 18),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 12)
  ) 

d_accuracy_block_morph <- 
  d_trials_block %>% 
  filter(Morph != 50) %>% 
  group_by(SID, Morph, block) %>% 
  summarize(accuracy = mean(accuracy, na.rm = TRUE)) %>% 
  group_by(Morph, block) %>% 
  multi_boot_standard(col = "accuracy") %>% 
  ungroup()

d_accuracy_block_morph %>% 
  ggplot(aes(
    x = Morph, 
    y = mean, 
    col = factor(block), 
    group = factor(block)
  )) + 
  geom_line() + 
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper), 
                  position = position_dodge(width = 4)) + 
  geom_hline(yintercept = .5, lty = 2) + 
  ylim(0,1) + 
  ylab("Proportion Accurate") + 
  xlab("Morph level") + 
  labs(title = "Mean accuracy by morph level") +
  scale_colour_solarized(name = "block") + 
  ggthemes::theme_few() +
  scale_x_continuous(breaks = c(60, 70, 100)) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 18),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 12)
  ) 

d_accuracy_block <- 
  d_trials_block %>% 
  filter(!is.na(accuracy)) %>% 
  group_by(SID, block) %>% 
  summarize(accuracy = mean(accuracy, na.rm = TRUE)) %>% 
  ungroup() %>% 
  group_by(block) %>% 
  multi_boot_standard(col = "accuracy") %>% 
  ungroup()

d_accuracy_block %>% 
  ggplot(aes(block, mean)) +
  geom_col() +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  labs(
    x = "Block",
    y = "Mean Accuracy",
    title = "Mean Accuracy by Test Block"
  ) +
  scale_y_continuous(labels = scales::percent) +
  ggthemes::theme_few() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 18),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 12)
  ) 
```


```{r eval=FALSE}

# ggplot(all_data, aes(x = t, y = y)) +
#   geom_point(alpha = 0.3) +
#   facet_wrap(~ trial, scales = "free_x")
# 
# trial_proportions <-
#   all_data %>%
#   filter(!is.na(trial)) %>%
#   group_by(sid, trial) %>%
#   mutate(
#     trial_length = max(t) - min(t),
#     look = !is.na(x) | !is.na(y)
#   ) %>%
#   mutate(look = case_when(
#     look ~ "looking",
#     !look ~ "not_looking"
#   )) %>%
#   ungroup() %>%
#   count(sid, trial, look, Morph) %>%
#   spread(look, n) %>%
  # left_join(
  #   demographics %>% select(SID, age),
  #   by = c("sid" = "SID")
  # ) %>%
#   replace_na(list(looking = 0, not_looking = 0)) %>% 
#   mutate(prop_looking = looking / (looking + not_looking))
# 
# morph_proportions <- 
#   trial_proportions %>% 
#   group_by(Morph) %>% 
#   multi_boot_standard(col = "prop_looking")
# 
# 
#   
# morph_proportions %>% 
#   ggplot(aes(as.factor(Morph), mean)) +
#   geom_col() +
#   geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
#   labs(
#     x = "Morph level",
#     y = "Proportion of trial looking",
#     title = "Proportion of trial spent looking at experimenter"
#   ) +
#   ggthemes::theme_few() +
#   theme(
#     plot.title = element_text(hjust = 0.5, size = 18),
#     axis.title = element_text(size = 16),
#     axis.text = element_text(size = 12)
#   ) 
# 
# trial_lengths <- 
#   all_data %>% 
#   mutate(trial_length = offset - onset) %>% 
#   group_by(sid, trial) %>% 
#   slice(1) %>% 
#   ungroup() %>% 
#   group_by(Morph) %>% 
#   summarize(mean_length = mean(trial_length))
# 
# trial_lengths %>% 
#   ggplot(aes(as.factor(`Morph`), mean_length)) +
#   geom_col()
# 
# 
# 
#   
#     
#   
  

# +
  #lims(x = c(0, 1920), y = c(0,1080))
```

```{r}
d %>% 
  filter(t >= 120, t <= 190) %>% 
  ggplot(aes(x = t, y = x)) +
  geom_point()
```


```{r}
#Visualizing looking behavior across different morph levels.

trial_proportions <- 
  all_data %>% 
  filter(!is.na(trial)) %>% 
  group_by(sid, trial) %>% 
  mutate(
    trial_length = max(t) - min(t),
    look_captured = !is.na(x) | !is.na(y)
  ) %>% 
  mutate(look = case_when(
    look_captured ~ "looking",
    !look_captured ~ "not_looking"
  )) %>% 
  ungroup() %>% 
  count(sid, trial, look, Morph) %>% 
  spread(look, n) %>% 
  left_join(
    demographics %>% select(SID, age),
    by = c("sid" = "SID")
  ) %>%
  
  replace_na(list(looking = 0, not_looking = 0)) %>% 
  mutate(prop_looking = looking / (looking + not_looking))

trial_lengths <-  
  d_trials %>% 
  mutate(length = offset - onset) %>% 
  filter(length > 0) %>% 
  arrange(length)

trial_lengths %>% 
  ggplot(aes(as.factor(Morph), length)) +
  geom_boxplot() +
  coord_cartesian(ylim = c(0, 15)) +
  ggthemes::theme_few()





morph_proportions <- 
  trial_proportions %>% 
  group_by(Morph) %>% 
  multi_boot_standard(col = "prop_looking")

morph_proportions %>% 
  ggplot(aes(as.factor(Morph), mean)) +
  geom_col() +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  labs(
    x = "Morph level",
    y = "Proportion of trial looking",
    title = "Proportion of Trial Spent Looking at Experimenter"
  ) +
  ggthemes::theme_few() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 18),
    axis.title = element_text(size = 16),
    axis.text = element_text(size = 12)
  ) 

morph_proportions_per_subject <-  
  trial_proportions %>% 
  group_by(sid, Morph) %>% 
  summarize(mean_prop_looking = mean(prop_looking))

morph_proportions_per_subject %>% 
  ggplot(aes(as.factor(Morph), mean_prop_looking)) +
  geom_col() +
  labs(
    x = "Morph",
    y = "Mean percentage of trial looking"
  ) +
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~ sid)

morph_proportions_per_subject %>% 
  ggplot(aes(`Morph`, mean_prop_looking)) +
  geom_point() +
  labs(
    x = "Morph",
    y = "Mean percentage of trial looking"
  ) +
  coord_cartesian(ylim = c(0, 1))

accuracy_looking <- 
  trial_proportions %>% 
  left_join(
    all_data %>% select(sid, trial, accuracy)
  ) %>% 
  group_by(sid, trial) %>% 
  slice(1) %>% 
  ungroup() %>% 
  group_by(accuracy) %>% 
  multi_boot_standard(col = "prop_looking")


```

```{r eval=FALSE}

lmer_data <- 
  trial_proportions %>% 
  rename(morph = Morph) %>% 
  mutate(
    morph = factor(morph),
    trial = factor(trial),
    age_c = as.numeric(langcog::scale(age, scale = FALSE))
  )

lmer_data$morph <- relevel(lmer_data$morph, ref = "100")
  
maximal_mod <- 
  lmerTest::lmer(
    prop_looking ~ morph * age_c + 
      (morph | sid) + (1 | trial),
    data = lmer_data, REML = FALSE
  )
  
g_lm <-summary(maximal_mod)

g_lm
```
```{r}
#Trial by trial visualization

trial_viz <- 
  all_data %>% 
  group_by(sid, trial) %>% 
  mutate(
    trial_time = t - min(t),
    bin = (trial_time %/% 0.5) * 0.5
  ) %>% 
  ungroup() %>% 
  arrange(bin, sid) %>% 
  mutate(looking = !is.na(x) & !is.na(y)) %>% 
  select(trial_time, bin, looking, everything()) 

trial_viz_n <- 
  trial_viz %>% 
  group_by(bin, sid, trial) %>% 
  slice(1) %>% 
  ungroup() %>% 
  count(bin)

trial_viz_ci <- 
  trial_viz %>% 
  group_by(bin) %>% 
  multi_boot_standard(col = "looking") %>% 
  ungroup() %>% 
  mutate(axis_position = bin + 0.25) %>% 
  left_join(
    trial_viz_n,
    by = c("bin")
  )

trial_viz_ci %>% 
  filter(bin <= 10) %>% 
  ggplot(aes(axis_position, mean)) +
  geom_point(aes(size = n)) +
  geom_line() +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  labs(
    x = "time after beginning of trial (seconds)",
    y = "mean proportion looking at experimenter",
    title = "Time course of proportion looking\nat experimenter across trials",
    size = "Number of trials\nrepresented"
  ) +
  scale_x_continuous(breaks = seq(from = 0, to = 10, by = 0.5)) +
  scale_size_continuous(breaks = seq(from = 700, to = 0, by = -100), range = c(1, 4.5)) +
  ggthemes::theme_few() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 18),
    plot.subtitle = element_text(hjust = 0.5, size = 12),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 8)
  ) 
  
  
```

```{r}
#Trial visualization, backwards from calibration

trial_viz_backwards <-
  all_data %>% 
  group_by(sid, trial) %>% 
  mutate(
    t_before_decision = t - max(t),
    time_bin = (t_before_decision %/% 0.5) * 0.5  
  ) %>% 
  ungroup() %>% 
  arrange(time_bin, sid) %>% 
  mutate(looking = !is.na(x) & !is.na(y)) %>% 
  select(t_before_decision, time_bin, sid, everything())

trial_viz_n_backwards <- 
  trial_viz_backwards %>% 
  group_by(time_bin, sid, trial) %>% 
  slice(1) %>% 
  ungroup() %>% 
  count(time_bin)

trial_viz_ci_backwards <- 
  trial_viz_backwards %>% 
  group_by(time_bin) %>% 
  multi_boot_standard(col = "looking") %>% 
  ungroup() %>% 
  mutate(axis_position = time_bin - 0.25) %>% 
  left_join(
    trial_viz_n_backwards,
    by = c("time_bin")
  )

trial_viz_ci_backwards %>% 
  filter(time_bin >= -6) %>% 
  ggplot(aes(axis_position, mean)) +
  geom_point(aes(size = n)) +
  geom_line() +
  geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2) +
  labs(
    x = "time before decision (seconds)",
    y = "mean proportion looking at experimenter",
    title = "Timecourse of children's referencing\nof experimenter prior to decision",
    caption = "Child's decision occurs at time 0",
    size = "Number of trials\nrepresented"
  ) +
  scale_size_continuous(
    breaks = seq(from = 700, to = 0, by = -100), 
    range = c(1, 4.5)
  ) +
  scale_x_continuous(breaks = seq(from = -6, to = 0, by = 0.5)) +
  ggthemes::theme_few() +
  theme(
    plot.title = element_text(hjust = 0.5, size = 18),
    plot.subtitle = element_text(hjust = 0.5, size = 12),
    axis.title = element_text(size = 14),
    axis.text = element_text(size = 8)
  ) 


mean_trial_length <- 
  d_trials %>% 
  mutate(trial_length = offset - onset) %>% 
  filter(trial_length > 0) %>% 
  summarise(mean = mean(trial_length))
```

